name: deploy
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.ARN_IAM_ROLE }}
          aws-region: ap-northeast-1
      - uses: aws-actions/setup-sam@v2
      - run: pip install poetry
      - run: make build
      - run: make sam-validate package deploy
      - run: make describe
      - run: tar cf layers.tar layers/ template.yml
      - uses: actions/upload-artifact@v3
        with:
          name: layers.tar
          path: layers.tar
